### ISSUE TITLE
script does not run as a service

### ISSUE THREAD

**Issue by RemcoAA** [akamai/siem-integration-connector-packages#1]
Hi,

we are trying to install the SIEM collector in an Azure environment in an automated way but we are running into some issues with the script.

Instead of using the init.d option we want to run this as a service via systemctl but there are two issues in the script both with this line:

```
java -Dfile.encoding=UTF-8 -Xmx2048m -Xms2048m \
            -DCEFConnector.kill.mark.dummy=CEFCONNECTOR.KILL.MARK \
            -jar CEFConnector-1.7.5.jar 1>>/dev/null 2>>/dev/null &
```

1. the script can only be started from the /opt/CEFConnector/bin folder otherwise the script can not locate the file CEFConnector-1.7.5.jar
2. The script does not want to run as a service because of the '&' at the end. 

Can these issues be solved in the source file, so our automated deployment can just download the code from git and we don't have to modify this first in our pipelines?

**Comment by RemcoAA** [comment]
@jrobins04 I noticed you recently updated the code, could you have a look at this issue and advise us how we can get this working.
We noticed the script is crashing on a regular basis because of connectivity issues with Akamai, for this reason we need to set it up as a service so it will restart.

`[ERROR] 2023-07-30 09:27:08,041 [main] net.meta.cefconnector.CEFConnectorApp:start:235- context {mode=Offset Based, requestUrlHost=https://cloudsecurity.akamaiapis.net, configIds=[90908], fetch interval=60000ms, fetch size=200000, Number of consumers=10, Proxy Host=proxy, Proxy Port=3128, data offset=d41d8;iUb6KRbtVfHaMeBQP5b8bV_E2X8osS-v_CxDVpHFU__1EAKzDU8rtFyb3XSbVp0Uutl641Svmky62ULjDIeSfOK5UsiQBsW3wu-G1mvw7k3DbgXRacXZg77DaQ}
[ERROR] 2023-07-30 09:27:08,041 [main] net.meta.cefconnector.CEFConnectorApp:start:236- Error Retrieving Security Events.
javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
    at sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1697) ~[?:?]
    at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1515) ~[?:?]
    at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1417) ~[?:?]
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:456) ~[?:?]
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:427) ~[?:?]
    at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436) ~[httpclient-4.5.13.jar:4.5.13]
    at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.upgrade(DefaultHttpClientConnectionOperator.java:191) ~[httpclient-4.5.13.jar:4.5.13]
    at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.upgrade(PoolingHttpClientConnectionManager.java:392) ~[httpclient-4.5.13.jar:4.5.13]
    at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:428) ~[httpclient-4.5.13.jar:4.5.13]
    at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.5.13.jar:4.5.13]
    at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[httpclient-4.5.13.jar:4.5.13]
    at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.13.jar:4.5.13]
    at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.13.jar:4.5.13]
    at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.13.jar:4.5.13]
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.13.jar:4.5.13]
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108) ~[httpclient-4.5.13.jar:4.5.13]
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56) ~[httpclient-4.5.13.jar:4.5.13]
    at net.meta.cefconnector.akamai.AkamaiProvider.callAPI(AkamaiProvider.java:134) ~[CEFConnector-1.7.6.jar:?]
    at net.meta.cefconnector.akamai.AkamaiProvider.getSecurityEventsByOffset(AkamaiProvider.java:51) ~[CEFConnector-1.7.6.jar:?]
    at net.meta.cefconnector.akamai.AkamaiProvider.getSecurityEvents(AkamaiProvider.java:169) ~[CEFConnector-1.7.6.jar:?]
    at net.meta.cefconnector.CEFConnectorApp.start(CEFConnectorApp.java:142) [CEFConnector-1.7.6.jar:?]
    at net.meta.cefconnector.CEFConnectorApp.main(CEFConnectorApp.java:52) [CEFConnector-1.7.6.jar:?]
Caused by: java.io.EOFException: SSL peer shut down incorrectly
    at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:489) ~[?:?]
    at sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:478) ~[?:?]
    at sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160) ~[?:?]
    at sun.security.ssl.SSLTransport.decode(SSLTransport.java:111) ~[?:?]
    at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1507) ~[?:?]
    ... 20 more
[ERROR] 2023-07-30 09:27:08,042 [main] net.meta.cefconnector.CEFConnectorApp:main:54- Error occurred.
java.lang.IllegalArgumentException: Failed to pull from API after 5 tries.
    at net.meta.cefconnector.CEFConnectorApp.start(CEFConnectorApp.java:248) ~[CEFConnector-1.7.6.jar:?]
    at net.meta.cefconnector.CEFConnectorApp.main(CEFConnectorApp.java:52) [CEFConnector-1.7.6.jar:?]
[ERROR] 2023-07-30 09:27:08,042 [main] net.meta.cefconnector.CEFConnectorApp:main:55- Connector is stopping...`

**Comment by jrobins04** [comment]
@RemcoAA is this an intermittent issue or you never have gotten CEF Connector working?

**Comment by RemcoAA** [comment]
Hi @jrobins04  we got the CEF connector working and do receive the events in Azure Sentinel but the connector is crashing every time after a couple of days with the above errors.

**Comment by viniciusazevedo-redbelt** [comment]
Hello @RemcoAA and @jrobins04 , I'm experiencing the same issue in my environment. Does anyone know the root cause or how to resolve it?
